# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3ffc823b988111a1aef5baeaed5e4a47e451048c5e3f88d1d525e7928704cfdb94cc7562ba0b28340c032592215102a960fbe86ab23ac8405354140d90450642

test:
  secret_key_base: a977a6bee90307db5112e3da9bf372c87e64aefd31928345a05e7526955d8df17ff5869ea9a9ab07e6c9a972e2f0f90a0187f8df4c6b46721b8ae151e64ce2e5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
