Photo.destroy_all

photos = Photo.create([
  {
  image_url: "1.JPG" 
  }, {
  image_url: "2.JPG"
  }, {
  image_url: "3.JPG"
  }, {
  image_url: "4.JPG"
  }, {
  image_url: "5.JPG"
  }, {
  image_url: "6.JPG"
  }, {
  image_url: "7.JPG"
  }, {
  image_url: "8.JPG"
  }, {
  image_url: "9.JPG"
  }, {
  image_url: "10.JPG"
  }, {
  image_url: "11.JPG"
  }, {
  image_url: "12.JPG"
  }, {
  image_url: "13.JPG"
  }, {
  image_url: "14.JPG"
  }, {
  image_url: "15.JPG"
  }, {
  image_url: "16.JPG"
  }, {
  image_url: "17.JPG"
  }, {
  image_url: "18.JPG"
  }, {
  image_url: "19.JPG"
  }, {
  image_url: "20.JPG"
  }, {
  image_url: "21.JPG"
  }, {
  image_url: "22.JPG"
  }, {
  image_url: "23.JPG"
  }, {
  image_url: "24.JPG"
  }, {
  image_url: "25.JPG"
  }, {
  image_url: "26.JPG"
  }, {
  image_url: "27.JPG"
  }, {
  image_url: "28.JPG"
  }, {
  image_url: "29.JPG"
  }, {
  image_url: "30.JPG"
  }, {
  image_url: "31.JPG"
  }, {
  image_url: "32.JPG"
  }, {
  image_url: "33.JPG"
  }, {
  image_url: "34.JPG"
  }, {
  image_url: "35.JPG"
  }, {
  image_url: "36.JPG"
  }, {
  image_url: "37.JPG"
  }, {
  image_url: "38.JPG"
  }, {
  image_url: "39.JPG"
  }, {
  image_url: "40.JPG"
  }, {
  image_url: "41.JPG"
  }, {
  image_url: "42.JPG"
  }, {
  image_url: "43.JPG"
  }, {
  image_url: "44.JPG"
  }, {
  image_url: "45.JPG"
  }, {
  image_url: "46.JPG"
  }, {
  image_url: "47.JPG"
  }, {
  image_url: "48.JPG"
  }, {
  image_url: "49.JPG"
  }, {
  image_url: "50.JPG"
  }, {
  image_url: "51.JPG"
  }, {
  image_url: "52.JPG"
  }, {
  image_url: "53.JPG"
  }, {
  image_url: "54.JPG"
  }, {
  image_url: "55.JPG"
  }, {
  image_url: "56.JPG"
  }, {
  image_url: "57.JPG"
  }, {
  image_url: "58.JPG"
  }, {
  image_url: "59.JPG"
  }, {
  image_url: "60.JPG"
  }, {
  image_url: "61.JPG"
  }, {
  image_url: "62.JPG"
  }, {
  image_url: "63.JPG"
  }, {
  image_url: "64.JPG"
  }, {
  image_url: "65.JPG"
  }, {
  image_url: "66.JPG"
  }, {
  image_url: "67.JPG"
  }, {
  image_url: "68.JPG"
  }, {
  image_url: "69.JPG"
  }, {
  image_url: "70.JPG"
  }, {
  image_url: "71.JPG"
  }, {
  image_url: "72.JPG"
  }, {
  image_url: "73.JPG"
  }, {
  image_url: "74.JPG"
  }, {
  image_url: "75.JPG"
  }, {
  image_url: "76.JPG"
  }, {
  image_url: "77.JPG"
  }, {
  image_url: "78.JPG"
  }, {
  image_url: "79.JPG"
  }, {
  image_url: "80.JPG"
  }, {
  image_url: "81.JPG"
  }, {
  image_url: "82.JPG"
  }, {
  image_url: "83.JPG"
  }, {
  image_url: "84.JPG"
  }, {
  image_url: "85.JPG"
  }, {
  image_url: "86.JPG"
  }, {
  image_url: "87.JPG"
  }, {
  image_url: "88.JPG"
  }, {
  image_url: "89.JPG"
  }, {
  image_url: "90.JPG"
  }, {
  image_url: "91.JPG"
  }, {
  image_url: "92.JPG"
  }, {
  image_url: "93.JPG"
  }, {
  image_url: "94.JPG"
  }, {
  image_url: "95.JPG"
  }, {
  image_url: "96.JPG"
  }
])